### ISSUE TITLE
credentials not given to <Layout> Component

### ISSUE THREAD

**Issue by beldur** [alexluong/gatsby-packages#11]
Hi,

the credentials from `pluginOptions` in `wrapRootElement` are not attached to the `<Layout>` component as props.

So if you set the `apiKey` in the plugin options instead of an environment variable, the key will be undefined and the initialization will fail.

See: https://github.com/alexluong/gatsby-packages/blob/master/packages/gatsby-plugin-firebase/gatsby-browser.js#L5

**Comment by alexluong** [comment]
@beldur Thank you for catching the issue. Fixed and released a new version!
