### ISSUE TITLE
Analytics and Performance Don't Work with gatsby-plugin-firebase

### ISSUE THREAD

**Issue by dimileeh** [alexluong/gatsby-packages#12]
According to Firebase docs, in order to enable Google Analytics inside a Firebase-enabled app, all you need is to import firebase/app.

Performance is also enabled by importing firebase/performance, followed by ```const perf = firebase.performance().```

However, when using `gatsby-plugin-firebase`, I just can't make Analytics and Performance work. I mean, when I create the production build and open the page in the Chrome browser, the Tag Assistant extension doesn't show any tags at all.

I can, however, create tag events by running `firebase.analytics().LogEvent("my_event")`.
In this case, the Tag Assistant does show one tag, but still says that Google Analytics is not enabled.

Here's how I created `firebase` and `perf` variables:

```
import { React, useState } from 'react'
import { useFirebase } from "gatsby-plugin-firebase"

function FirebaseFunctions() {
  const [firebase, setFirebase] = useState(null);
  const [perf, setPerf] = useState(null);

  useFirebase(firebase => {
    setFirebase(firebase);
    setPerf(firebase.performance());
    firebase.analytics().logEvent('app_rendered');
  }, [])

  return [firebase, perf]
}

export default FirebaseFunctions
```

After that, I call this hook in my ```Layout``` function like this:
```const [ firebase, perf ] = FirebaseFunctions();```

Am I doing something wrong, or is it that this plugin doesn't enable Analytics?

**Comment by alexluong** [comment]
I'm not super familiar with the analytics and performance functionality of Firebase. I'd welcome any help if you feel like going over the source code of the package.

**Comment by davwheat** [comment]
I didn't think analytics was working either when I created my PR to add them to this project but it turns out they do work fine.

It seems Firebase doesn't like showing your stats even up to 2 weeks after you enable it on your project and add it to your app.

This web app is built with Gatsby and this plugin and stats are now being reported:

![image](https://user-images.githubusercontent.com/7406822/72635759-7ff53080-3955-11ea-9718-c4b5af594ab7.png)

Here's where I used it:

```js
Firebase.analytics().setUserProperties({ allowed_notifications: "yes" })
```

**Comment by alexluong** [comment]
I published v2 of the plugin. Please create another issue if this is a problem.

**Comment by dimileeh** [comment]
Sorry, guys, I've lost track of this reported issue. As @davwheat pointed out, Analytics and Performance turned out to work just fine. My statement that they don't work were based on the fact that the Google Tag Analyser Chrome extension weren't displaying any tags for my Gatsby website with `gatsby-plugin-firebase`. I guess it's the Chrome extension's problem.

Thank you very much for the v2 update, @alexluong!
