### ISSUE TITLE
Documentation when using Messaging

### ISSUE THREAD

**Issue by joeynimu** [alexluong/gatsby-packages#2]
I am trying to setup which uses the `messaging` option and I am struggling a bit to figure things out. Do you mind adding a guide on how to setup messaging? I'd be happy to do a PR for this if I get an idea of how to set it up.

Thanks

**Comment by alexluong** [comment]
Hey @joeynimu, I don't use the `messaging` feature by Firebase myself, so I'm not familiar with it.

If you can give me an example of how you're using it in other React apps, maybe I can help figure out how to set up it for Gatsby.
