### ISSUE TITLE
Old version if install with npm

### ISSUE THREAD

**Issue by UK090483** [alexluong/gatsby-packages#5]
Hey Alex,
when I run npm install  gatsby-plugin-firebase (as mentioned in the dos), I get some old version that doesn't work at all.
I copyed the files from this repo manualy and this seems to work!
Maybe I'm to stupid and did something wrong but I acualy just followed the docs ...

All the best K

**Comment by alexluong** [comment]
@UK090483 Hey, this is actually my bad. I'm experimenting with some new version and messed up the package. If you can run `npm install gatsby-plugin-firebase@0.1.3`, everything should work.

Sorry for the late response too.

**Comment by alexluong** [comment]
See #6 and report any issues over there if you can. Thank you!
