### ISSUE TITLE
useFirebase hook generating errors

### ISSUE THREAD

**Issue by davwheat** [alexluong/gatsby-packages#6]
When using `useFirebase(firebase => { ... })` I keep getting errors.

```
TypeError: Object(...) is not a function
```

```js
> 20 |  useFirebase(firebase => {
  21 |    setStorageRef(firebase.storage.ref("uploads"))
  22 |  }, [])
```

---

If I try to use the `useContext` method, I then get this error...

```
TypeError: Cannot read property '_context' of undefined
```
```js
// useContext
// E:/Git Repos/oathall-leavers-site/node_modules/react/cjs/react.development.js:1603
  1600 | {
  1601 |   !(unstable_observedBits === undefined) ? warning$1(false, 'useContext() second argument is reserved for future ' + 'use in React. Passing it is not supported. ' + 'You passed: %s.%s', unstable_observedBits, typeof unstable_observedBits === 'number' && Array.isArray(arguments[2]) ? '\n\nDid you call array.map(useContext)? ' + 'Calling Hooks inside a loop is not supported. ' + 'Learn more at https://fb.me/rules-of-hooks' : '') : void 0; // TODO: add a more generic warning for invalid values.
  1602 | 
> 1603 |   if (Context._context !== undefined) {
  1604 |     var realContext = Context._context; // Don't deduplicate because this legitimately causes bugs
  1605 |     // and nobody should be using this in existing code.
  1606 | 
```

**Comment by jmaicaaan** [comment]
Same here.

**Comment by AaronBentley** [comment]
Ditto for me too, it appears the 0.2.0-rc release is incomplete.

After having a dig through [the plugin code ](https://github.com/alexluong/gatsby-packages/tree/firebase/0.2.0/packages/gatsby-plugin-firebase/src)it appears to be missing a few files/features and has no export (named or default) to expose the useFirebase hook.

@alexluong can you confirm these findings? 😀

**Comment by davwheat** [comment]
I wondered why IntelliSense didn't autocomplete the import.

**Comment by arnars** [comment]
Same issue. I also had to add my credentials into gatsby-config.js for it to work.
```
 options: {
                credentials: {
                    apiKey: `${process.env.GATSBY_FIREBASE_API_KEY}`,
                    authDomain: `${process.env.GATSBY_FIREBASE_AUTH_DOMAIN}`,
                    databaseURL: `${process.env.GATSBY_FIREBASE_DATABASE_URL}`,
                    projectId: `${process.env.GATSBY_FIREBASE_PROJECT_ID}`,
                    storageBucket: `${process.env.GATSBY_FIREBASE_STORAGE_BUCKET}`,
                    messagingSenderId: `${process.env.GATSBY_FIREBASE_MESSAGING_SENDER_ID}`,
                    appId: `${process.env.GATSBY_FIREBASE_APP_ID}`,
                },
                features: {
                    auth: true,
                    database: false,
                    firestore: false,
                    storage: false,
                    messaging: false,
                    functions: true,
                },
            },
```

**Comment by alexluong** [comment]
Hey folks, so sorry about this.

Run

```
npm install gatsby-plugin-firebase@^0.1.4
```

This should fix it. I tried to upload an experimental `0.2.0` version but ended up messing things up.

Let me know if this doesn't fix it.

@davwheat @jmaicaaan @AaronBentley @arnars

**Comment by jmaicaaan** [comment]
It is working using that version :) Thanks!

**Comment by alexluong** [comment]
Awesome.

I'm super glad you're using my project. I'm working on a new version with some breaking changes, and I'd love to hear what you think about it.

The new version should simplify a lot of things and let you use Firebase like you're used to on the client side (create-react-app).

I created an [RFC](https://github.com/alexluong/gatsby-packages/issues/7) for it. Would love to hear your thoughts. Thank you!
