### ISSUE TITLE
[RFC] gatsby-plugin-firebase v0.2.0

### ISSUE THREAD

**Issue by alexluong** [alexluong/gatsby-packages#7]
Recently, I've learned that with Gatsby, you can import firebase directly and use it without any issue on the server side. There will be an ugly warning, but everything should work just fine.

Therefore, inspired by [`gatsby-theme-firebase`](https://github.com/epilande/gatsby-theme-firebase), I'd like to make some changes to this package.

## Mission

This package `gatsby-plugin-firebase` aims to help initializing a Firebase app for you without forcing you to change how you've been using Firebase before. You should be able to use other packages on top of firebase like [`react-firebase-hooks`](https://github.com/CSFrequency/react-firebase-hooks) without any issues.

## Set up

```
npm install firebase gatsby-plugin-firebase # version 0.2.0
```

```js
// gatsby-config.js

module.exports = {
  plugins: [
    {
      resolve: "gatsby-plugin-firebase",
      options: {
        credentials: {
          apiKey: process.env.FIREBASE_API_KEY,
          authDomain: process.env.FIREBASE_AUTH_DOMAIN,
          databaseURL: process.env.FIREBASE_DATABASE_URL,
          projectId: process.env.FIREBASE_PROJECT_ID,
          storageBucket: process.env.FIREBASE_STORAGE_BUCKET,
          messagingSenderId: process.env.FIREBASE_MESSAGING_SENDER_ID,
          appId: process.env.FIREBASE_APP_ID,
        },
      }
    }
  ]
}
```

Now, instead of the `features` option, you can import whichever inside `gatsby-browser.js`:

```js
// gatsby-browser.js

import "firebase/auth"
import "firebase/firestore"
import "firebase/storage"
```

## Usage

To use firebase, you can import it from `gatsby-plugin-firebase`

```jsx
import React from "react"
import firebase from "gatsby-plugin-firebase"

export default () => {
  const [data, setData] = React.useState(null)
  React.useEffect(() => {
    firebase.firestore().doc("data/sample").get().then(snapshot => {
      setData(snapshot.data())
    })
  })

  return <MyComponent data={data} />
}
```

I'm also working on an optional `useAuth` hook that listens to `onAuthStateChange`:

```js
import { useAuth } from "gatsby-plugin-firebase"

const { isInitializing, isLoggedIn, user } = useAuth()
```

**Comment by davwheat** [comment]
Sounds great!

When you get the chance, could you try to add Performance Monitoring to the plugin? [It's currently in Beta for the web.](https://firebase.google.com/docs/perf-mon/get-started-web)

**Comment by jmaicaaan** [comment]
@alexluong  - What's the main difference on separating the imports? Much easier on the plugin specifically?

**Comment by alexluong** [comment]
@jmaicaaan it's how Gatsby works. They render the site on the server once, and then rehydrates to a client React app on the browser. Therefore, with packages like `firebase` that only works on the browser, it can be tricky sometimes.

**Comment by jmaicaaan** [comment]
@alexluong - Got it. Thanks! 👍

**Comment by alexluong** [comment]
Published v2
