### ISSUE TITLE
No dependencies in package.json, so gatsby-plugin-firebase doesn't complain if firebase is outdated

### ISSUE THREAD

**Issue by asktree** [alexluong/gatsby-packages#9]
gatsby develop generates the following error: 

```
`ERROR #98123  WEBPACK

Generating SSR bundle failed

Can't resolve 'firebase/analytics' in 'C:\Users\agrippa\Documents\GitHub\gallery-client\node_modules\gatsby-plugin-firebase\src'
```

Relevant gatsby-config snippet: 
```
{
      resolve: "gatsby-plugin-firebase",
      options: {
        features: {
          auth: true,
          database: false,
          firestore: false,
          storage: false,
          messaging: false,
          functions: false,
          performance: false,
          analytics: false,
        },
      },
    },
```

I shouldn't need to install firebase/analytics to use this plugin. What's going on?

**Comment by asktree** [comment]
The issue was that I didn't have the most recent version of firebase. This package should probably specify dependencies :P

**Comment by alexluong** [comment]
Thanks for the report. I'll keep in mind the issue and make sure it wouldn't happen for v0.2.

**Comment by marcomelilli** [comment]
@alexluong In package.json I found: "firebase": "6.x". 
But it seems it doesn't work with this version... I needed to upgrade to firebase 7.5.0
